### ISSUE TITLE
Error message is wrong when there is no or incorrect failure callback supplied

### ISSUE THREAD

**Issue by misi444** [topheman/sensorsChecker.js#1]
sensorsChecker.js line 92. The error message complains about the success callback even when the problem is with the failure callback.

**Comment by topheman** [comment]
https://github.com/topheman/sensorsChecker.js/blob/f404979d1681182d069aa91ccf5a67938c12bcde/sensorsChecker.js#L91-L93

Hie @misi444, I assume the following fix would do the trick, wouldn't it ?

```diff
            if(typeof failure !== "function"){
-                throw new Error("success callback missing");
+                throw new Error("failure callback missing");
            }
```

This is a typo. The failure callback should still be mandatory.

**Comment by misi444** [comment]
Yes, this is what I thought as well. The mandatoriness of the failure callback is a design decision, I accept it if you would like to keep it as it is.

**Comment by topheman** [comment]
@misi444 Thanks for reporting the typo. I released a new version on [npm](https://www.npmjs.com/package/sensors-checker), you can see the [release log here](https://github.com/topheman/sensorsChecker.js/releases/tag/v1.0.1)

**Comment by misi444** [comment]
Thank you!
